name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - cycler==0.11
  - fonttools==4.34
  - h5py==3.7
  - kiwisolver==1.4
  - matplotlib==3.5
  - numpy==1.23
  - pillow==9.2
  - scipy==1.8